# Generated by Django 4.1.3 on 2022-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default='2000/01/01', verbose_name='日付')),
                ('news', models.CharField(max_length=1000, verbose_name='お知らせ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
            ],
        ),
    ]
