# Generated by Django 4.1.3 on 2022-12-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_news_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='お知らせ', max_length=30, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
