# Generated by Django 4.1.3 on 2022-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False, verbose_name='重要'),
        ),
    ]
