# Generated by Django 4.1.3 on 2022-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(default=4002555, max_length=30),
            preserve_default=False,
        ),
    ]
