# Generated by Django 4.1.3 on 2022-12-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
