# Generated by Django 4.1.3 on 2022-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_post_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'CustomUser'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(default='4801234'),
        ),
    ]
