# Generated by Django 4.1.3 on 2022-12-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raikan_kazu',
            field=models.IntegerField(default=0),
        ),
    ]
